cask "swipeaerospace" do # THE FILE IS GENERATED BY build-brew-cask.py
  version "v0.3.1"
  sha256 "c5dd94b925717f73f59dc51cfbcfb7bbe6443d606ddbf6743ae0ca621b9e4536"

  url "https://github.com/MediosZ/SwipeAeroSpace/releases/download/#{version}/SwipeAeroSpace.zip"
  name "SwipeAeroSpace"
  desc "SwipeAeroSpace is a tool to switch AeroSpace worksapces by swiping."
  homepage "https://github.com/MediosZ/SwipeAeroSpace"

  depends_on macos: ">= :ventura" # macOS 13

  postflight do
    system "xattr -d com.apple.quarantine #{appdir}/SwipeAeroSpace.app"
  end

  app "SwipeAeroSpace.app"
end
