cask "swipeaerospace" do # THE FILE IS GENERATED BY build-brew-cask.py
  version "v0.3.2"
  sha256 "11e370c1e9f781741cc1406eab87c369b4c8da6eef5de1f66c5655f282f1be25"

  url "https://github.com/MediosZ/SwipeAeroSpace/releases/download/#{version}/SwipeAeroSpace.zip"
  name "SwipeAeroSpace"
  desc "SwipeAeroSpace is a tool to switch AeroSpace worksapces by swiping."
  homepage "https://github.com/MediosZ/SwipeAeroSpace"

  depends_on macos: :ventura # macOS 13

  postflight do
    system "xattr -d com.apple.quarantine #{appdir}/SwipeAeroSpace.app"
  end

  app "SwipeAeroSpace.app"
end
