cask "swipeaerospace" do # THE FILE IS GENERATED BY build-brew-cask.sh
  version '0.1.7'
  sha256 "4f24e192238f4f326e97aad92c1da7b92005078cd5cb70b28687d3c95abd04a6"

  url "https://github.com/MediosZ/SwipeAeroSpace/releases/download/#{version}/SwipeAeroSpace.zip"
  name "SwipeAeroSpace"
  desc "SwipeAeroSpace is a tool to switch AeroSpace worksapces by swiping."
  homepage "https://github.com/MediosZ/SwipeAeroSpace"

  depends_on macos: ">= :ventura" # macOS 13

  postflight do
    system "xattr -d com.apple.quarantine #{appdir}/SwipeAeroSpace.app"
  end

  app "SwipeAeroSpace.app"
end
